/** Static NFL conference/division map — ESPN list endpoint omits groups. */
export const NFL_DIVISIONS: Record<
  string,
  { conference: string; division: string }
> = {
  BUF: { conference: "AFC", division: "AFC East" },
  MIA: { conference: "AFC", division: "AFC East" },
  NE: { conference: "AFC", division: "AFC East" },
  NYJ: { conference: "AFC", division: "AFC East" },
  BAL: { conference: "AFC", division: "AFC North" },
  CIN: { conference: "AFC", division: "AFC North" },
  CLE: { conference: "AFC", division: "AFC North" },
  PIT: { conference: "AFC", division: "AFC North" },
  HOU: { conference: "AFC", division: "AFC South" },
  IND: { conference: "AFC", division: "AFC South" },
  JAX: { conference: "AFC", division: "AFC South" },
  TEN: { conference: "AFC", division: "AFC South" },
  DEN: { conference: "AFC", division: "AFC West" },
  KC: { conference: "AFC", division: "AFC West" },
  LV: { conference: "AFC", division: "AFC West" },
  LAC: { conference: "AFC", division: "AFC West" },
  DAL: { conference: "NFC", division: "NFC East" },
  NYG: { conference: "NFC", division: "NFC East" },
  PHI: { conference: "NFC", division: "NFC East" },
  WSH: { conference: "NFC", division: "NFC East" },
  CHI: { conference: "NFC", division: "NFC North" },
  DET: { conference: "NFC", division: "NFC North" },
  GB: { conference: "NFC", division: "NFC North" },
  MIN: { conference: "NFC", division: "NFC North" },
  ATL: { conference: "NFC", division: "NFC South" },
  CAR: { conference: "NFC", division: "NFC South" },
  NO: { conference: "NFC", division: "NFC South" },
  TB: { conference: "NFC", division: "NFC South" },
  ARI: { conference: "NFC", division: "NFC West" },
  LAR: { conference: "NFC", division: "NFC West" },
  SF: { conference: "NFC", division: "NFC West" },
  SEA: { conference: "NFC", division: "NFC West" },
};
